Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |v|
    v.name = "05_k8s-minikube"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "docker" do |d|
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
    sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list

    sudo apt-get update
    sudo apt-get install -y kubectl

    curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
  SHELL

  config.vm.synced_folder "./config", "/home/vagrant/config"

  config.vm.network "private_network", ip: "192.168.56.6"
end

# On VM start, run the following command to start the minikube cluster
# ```bash minikube start```

# To view the minikube dashboard, run the following command
# ```bash minikube dashboard```


# Only needed because of the VM Setup
# Use the command below to proxy the kubernetes API server in the VM
# kubectl proxy --address=0.0.0.0 --disable-filter=true
# Then open the k8s dashboard at
# http://192.168.56.6:8001/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/
