# Build stage
FROM caddy:2.10-builder AS builder

RUN xcaddy build --with github.com/caddyserver/forwardproxy

# Final stage
FROM caddy:2.10-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

EXPOSE 3128

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
